networks:
  esd-network:                # key must be esd-network
    driver: bridge
    name: esd-network
services:
  rabbitmq:
    image: rabbitmq:3-management
    container_name: wattsapp-rabbit
    ports:
      - "5672:5672"
      - "15673:15672"         # Management UI on http://localhost:15672
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: password123
    volumes:
      - wattsapp_rabbitmq_data:/var/lib/rabbitmq
    networks:
      - esd-network

  driver:
    build:
      context: .
      dockerfile: driver/Dockerfile
    image: wattsapp/driver
    container_name: driver
    ports:
      - "5001:5001"            # changed from 5011 → 5001
    environment:
      - dbURL=mysql+mysqlconnector://root:jpPOaVCbCXnTWjDOBzPtDoRKYwqqiClR@caboose.proxy.rlwy.net:45033/driver
    networks:
      - esd-network

  booking:
    build:
      context: .
      dockerfile: booking/Dockerfile
    image: wattsapp/booking
    container_name: booking
    ports:
      - "5002:5002"
    environment:
      - dbURL=mysql+mysqlconnector://root:jpPOaVCbCXnTWjDOBzPtDoRKYwqqiClR@caboose.proxy.rlwy.net:45033/booking
    networks:
      - esd-network

  payment:
    build:
      context: .
      dockerfile: payment/Dockerfile
    image: wattsapp/payment
    container_name: payment
    ports:
      - "5003:5003"
    depends_on:
      - rabbitmq
    environment:
      - dbURL=mysql+mysqlconnector://root:jpPOaVCbCXnTWjDOBzPtDoRKYwqqiClR@caboose.proxy.rlwy.net:45033/payment
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=password123
    networks:
      - esd-network

  notification:
    build:
      context: .
      dockerfile: notification/Dockerfile
    image: wattsapp/notification
    container_name: notification
    ports:
      - "5004:5004"
    depends_on:
      - rabbitmq
    environment:
      - dbURL=mysql+mysqlconnector://root:jpPOaVCbCXnTWjDOBzPtDoRKYwqqiClR@caboose.proxy.rlwy.net:45033/notification
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=password123
    networks:
      - esd-network

  maintenance:
    build:
      context: .
      dockerfile: maintenance/Dockerfile
    image: wattsapp/maintenance
    container_name: maintenance
    ports:
      - "5005:5005"
    environment:
      - dbURL=mysql+mysqlconnector://root:jpPOaVCbCXnTWjDOBzPtDoRKYwqqiClR@caboose.proxy.rlwy.net:45033/maintenance
    networks:
      - esd-network

  view-slots:
    build:
      context: .
      dockerfile: view_slots/Dockerfile
    image: wattsapp/view-slots
    container_name: view-slots
    ports:
      - "5006:5006"
    environment:
      - DRIVER_URL=http://driver:5001
      - BOOKING_URL=http://booking:5002
      - OUTSYSTEMS_BASE_URL=https://personal-dftp1xlj.outsystemscloud.com/Status/rest/Status
    networks:
      - esd-network
    depends_on:
      - driver
      - booking
      
  report-fault:
    build:
      context: .
      dockerfile: report_fault/Dockerfile
    image: wattsapp/report-fault
    container_name: report-fault
    ports:
      - "5010:5010"
    environment:
      - MAINTENANCE_URL=http://maintenance:5005
      - BOOKING_URL=http://booking:5002
      - PAYMENT_URL=http://payment:5003
      - NOTIFICATION_URL=http://notification:5004
      - STATUS_URL=https://personal-dftp1xlj.outsystemscloud.com/Status/rest/Status
    networks:
      - esd-network
    depends_on:
      - maintenance
      - booking
      - payment
      - notification
      - rabbitmq

  handleNoShow:
    build:
      context: .
      dockerfile: handleNoShow/Dockerfile
    image: wattsapp/handleNoshow
    container_name: handleNoShow
    ports:
      - "5100:5100"
    environment:
      - DRIVER_URL=http://driver:5001
      - BOOKING_URL=http://booking:5002
      - PAYMENT_URL=http://payment:5003
      - RABBITMQ_HOST=rabbitmq
      - RABBITMQ_USER=admin
      - RABBITMQ_PASS=password123
    networks:
      - esd-network
    depends_on:
      - driver
      - booking
      - payment
      - rabbitmq
      
  make-booking:
    build:
      context: .
      dockerfile: Make-booking/Dockerfile
    image: wattsapp/make-booking
    container_name: make-booking
    environment:
      - PAYMENT_URL=http://payment:5002/payment/hold
      - BOOKING_URL=http://booking:5003/bookings
      - RABBITMQ_URL=amqp://admin:password123@rabbitmq:5672/%2F
    ports:
      - "5001:5001"
    depends_on:
      - payment
      - booking
      - rabbitmq
    networks:
      - esd-network
volumes:
  wattsapp_rabbitmq_data:

  