FROM python:3.10-slim

WORKDIR /app
# relative to docker build file
COPY handleNoShow/handleNoShow.py . 
COPY amqp.reqs.txt .
COPY http.reqs.txt .

RUN pip install --no-cache-dir -r http.reqs.txt -r amqp.reqs.txt
COPY amqp_lib.py invokes.py ./

CMD ["python", "handleNoShow.py"]


