FROM python:3.10-slim

WORKDIR /app
# relative to docker build file
COPY handleNoShow/handleNoShow.py . 

COPY http.reqs.txt .

RUN pip install --no-cache-dir -r http.reqs.txt

CMD ["python", "handleNoShow.py"]